FROM node:24 AS build-stage
WORKDIR /usr/src/app

COPY --chown=node:node . .

RUN npm ci

ENV VITE_BACKEND_URL=http://localhost:3000

USER node

RUN npm run test && npm run build

FROM nginx:1.29-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
