services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
