GET http://localhost:3000/todos/

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "text": "fix routes"
}

###

# Add id of todo you want to update in the url such as 6a6a5884b7bb88b92fa9edf8
PUT http://localhost:8080/api/todos/
Content-Type: application/json

{
 "text": "Fix routes!",
 "done": true
}

###

# Add id of todo you want to delete in the url such as 6a6a5884b7bb88b92fa9edf8
DELETE http://localhost:3000/todos/

